-- Microstates: 25% battalion manpower and stronger frontline demand.
NDefines.NAI.WANTED_UNITS_MANPOWER_DIVISOR = 5000
NDefines.NAI.WANTED_UNITS_WEIGHT_FRONTS_WANT = 0.55
NDefines.NAI.WANTED_UNITS_WEIGHT_FACTORIES = 0.3
NDefines.NAI.WANTED_UNITS_MIN_DEFENCE_FACTOR = 0.8
NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 0.85
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 0.65
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 0.9
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.8
NDefines.NAI.MAX_UNITS_FACTOR_FRONT_ORDER = 1.3
NDefines.NAI.DESIRED_UNITS_FACTOR_FRONT_ORDER = 1.25
NDefines.NAI.DESIRED_UNITS_FACTOR_AREA_ORDER = 0.45
NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 1.25
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.35
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 5
