"""Build 20 region-owned manufacturers from the reviewed authored design.

The mod replaces vanilla organizations, so each tree is deliberately self-contained.
No vanilla template include, script flag, country history or leader file is required.
"""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / 'design/regional-manufacturers.json'
OUTPUTS = {
    'mio': 'mod/common/military_industrial_organization/organizations/sof_regional_manufacturers.txt',
    'ideas': 'mod/common/ideas/sof_regional_manufacturers.txt',
    'loc': 'mod/localisation/simp_chinese/replace/sof_regional_manufacturers_l_simp_chinese.yml',
    'doc': 'docs/REGIONAL-MANUFACTURERS-ZH.md',
}

STAT_NAMES = {
    'reliability': '可靠性', 'build_cost_ic': '装备造价', 'production_cost_factor': '生产成本',
    'armor_value': '装甲', 'maximum_speed': '速度', 'soft_attack': '对人杀伤',
    'hard_attack': '对装甲杀伤', 'ap_attack': '穿甲', 'defense': '防御',
    'naval_range': '航程', 'naval_speed': '航速', 'sub_detection': '对潜探测',
    'sub_attack': '反潜攻击', 'naval_strike_attack': '对舰攻击',
    'air_range': '航程', 'air_agility': '机动性', 'air_bombing': '战略轰炸',
    'air_ground_attack': '对地攻击', 'air_attack': '防空',
    'fuel_consumption': '燃油消耗', 'torpedo_attack': '鱼雷攻击',
    'production_resource_need_factor': '生产资源需求',
    'production_efficiency_gain_factor': '生产效率增长',
    'production_efficiency_cap_factor': '生产效率上限',
}


def number(value):
    return format(value, '.6g')


def block(key, values):
    return f'{key} = {{ ' + ' '.join(f'{k} = {number(v)}' for k, v in values.items()) + ' }'


def completed(focuses):
    terms = ' '.join('has_completed_focus = ' + fid for fid in focuses)
    return 'OR = { ' + terms + ' }' if len(focuses) > 1 else terms


def gate(row, focuses, mio=False):
    # PREV is the owning country after entering the literal state scope, including
    # when the owning country is entered through the MIO's documented FROM scope.
    body = (f'has_capitulated = no {completed(focuses)} '
            f'{row["factory_state"]} = {{ is_owned_by = PREV is_fully_controlled_by = PREV }}')
    return 'FROM = { ' + body + ' }' if mio else body


def stats_text(values):
    return '、'.join(STAT_NAMES[k] + f'{v:+.0%}' for k, v in values.items())


def localized_focuses(row, field):
    return ' / '.join(row[field + '_names'])


def render(design):
    companies = design['manufacturers']
    mio = ['# Generated by tools/build_regional_manufacturers.py; authored source: design/regional-manufacturers.json.']
    ideas_by_slot = {}
    loc = ['l_simp_chinese:']
    def localize(key, value):
        value = value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        loc.append(f' {key}:0 "{value}"')

    localize('sof_regional_manufacturer_quality_header', '地方工艺')
    localize('sof_regional_manufacturer_production_header', '工场协作')
    documents = [
        '# 地区专属制造商', '',
        '20 个大区代表国家各有一家主打企业。所有企业都限制原籍及当前国家代码，兼容现行通用国策与旧地区树存档；控制厂址并完成实际工业国策后开放。占领其他大区不会获得该地专属企业。', '',
        '启用《Arms Against Tyranny》时使用原生军工组织：10% 专项科研、1 项起始工艺、4 项成长特质，后两项继续受工业国策约束。没有该 DLC 时同一家企业进入传统设计商对应槽位，聘用费用 125 政治点、解聘费用 10；科研同为 10%，装备加成仅为起始工艺。两种版本通过相反 DLC 条件隔离。', '',
        '数值只影响该企业承接的装备与生产线。一般起始强项 4–6%，代价 2–3%；完成全部成长后主打性能通常 8–10%，成本路线最多降低 6%，额外生产效率上限或增长 3%，资源需求最多降低 6%。不直接增加全国军工产能、全军攻防或额外科研槽。', '',
        '| 国家 | 企业与主打 | 起始强项 / 代价 | 厂址 | 解锁国策 |',
        '| --- | --- | --- | --- | --- |',
    ]
    for row in companies:
        tag = row['tag']
        key = row['id']
        initial = row['initial_equipment']
        initial_prod = row['initial_production']
        localize(key, row['name'])
        localize(key + '_legacy', row['name'])
        summary = stats_text(initial)
        if initial_prod:
            summary += ('；' if summary else '') + stats_text(initial_prod)
        full_equipment = dict(initial)
        full_production = dict(initial_prod)
        for trait in row['traits']:
            for target, values in [(full_equipment, trait.get('equipment', {})), (full_production, trait.get('production', {}))]:
                for stat, amount in values.items():
                    target[stat] = round(target.get(stat, 0) + amount, 6)
        full_summary = stats_text(full_equipment)
        if full_production:
            full_summary += '；' + stats_text(full_production)
        conditions = '完全控制' + row['factory_name'] + '，完成“' + localized_focuses(row, 'unlock') + '”。'
        localize(key + '_desc', row['description'] + '\n起始工艺：' + summary + '。专项科研：+10%。\n全部成长：' + full_summary + '。\n解锁：' + conditions)
        localize(key + '_legacy_desc', row['description'] + '\n起始工艺：' + stats_text(initial) + '。专项科研：+10%。\n解锁：' + conditions + '\n传统设计商版本仅提供起始装备工艺，不含军工组织成长。')
        localize(key + '_initial', row['initial_name'])
        localize(key + '_unlock_tt', '完全控制' + row['factory_name'] + '，并完成“' + localized_focuses(row, 'unlock') + '”。')
        localize(key + '_specialize_tt', '完成“' + localized_focuses(row, 'specialize') + '”。')
        localize(key + '_capstone_tt', '完成“' + localized_focuses(row, 'capstone') + '”。')
        mio.extend([
            '', key + ' = {', f' name = {key}', f' icon = GFX_idea_{row["picture"]}',
            f' allowed = {{ original_tag = {tag} tag = {tag} has_dlc = "Arms Against Tyranny" }}',
            f' available = {{ custom_trigger_tooltip = {{ tooltip = {key}_unlock_tt {gate(row, row["unlock"], True)} }} }}',
            ' equipment_type = { ' + ' '.join(row['equipment']) + ' }',
            ' research_categories = { ' + ' '.join(row['research_categories']) + ' }',
            ' research_bonus = 0.10', ' task_capacity = 2',
            ' tree_header_text = { text = sof_regional_manufacturer_quality_header x = 1 }',
            ' tree_header_text = { text = sof_regional_manufacturer_production_header x = 4 }',
            f' initial_trait = {{ name = {key}_initial',
        ])
        if initial:
            mio.append('  ' + block('equipment_bonus', initial))
        if initial_prod:
            mio.append('  ' + block('production_bonus', initial_prod))
        mio.append(' }')
        for i, trait in enumerate(row['traits']):
            token = key + '_trait_' + str(i + 1)
            localize(token, trait['name'])
            mio.extend([f' trait = {{ token = {token} name = {token}',
                        f'  icon = {trait["icon"]}',
                        '  position = { x = ' + str(1 if i % 2 == 0 else 4) + ' y = ' + str(i // 2) + ' }'])
            if i:
                mio.append(f'  any_parent = {{ {key}_trait_{i} }}')
            if i >= 2:
                field = 'specialize' if i == 2 else 'capstone'
                mio.append(f'  available = {{ custom_trigger_tooltip = {{ tooltip = {key}_{field}_tt FROM = {{ {completed(row[field])} }} }} }}')
            if trait.get('equipment'):
                mio.append('  ' + block('equipment_bonus', trait['equipment']))
            if trait.get('production'):
                mio.append('  ' + block('production_bonus', trait['production']))
            mio.append(' }')
        mio.extend([' ai_will_do = { factor = 1.15 }', '}'])

        legacy = [f' {key}_legacy = {{', f'  picture = {row["picture"]}',
                  f'  allowed = {{ original_tag = {tag} tag = {tag} NOT = {{ has_dlc = "Arms Against Tyranny" }} }}',
                  '  allowed_civil_war = { always = no }',
                  f'  available = {{ custom_trigger_tooltip = {{ tooltip = {key}_unlock_tt {gate(row, row["unlock"])} }} }}',
                  f'  cancel = {{ NOT = {{ {gate(row, row["unlock"])} }} }}',
                  '  cost = 125', '  removal_cost = 10',
                  '  research_bonus = { ' + ' '.join(k + ' = 0.10' for k in row['research_categories']) + ' }']
        # Production resource/efficiency modifiers do not have a per-line legacy
        # equivalent. The fallback intentionally carries only equipment effects.
        if initial:
            legacy.append('  equipment_bonus = {')
            for eq in row.get('legacy_equipment', row['equipment']):
                legacy.append('   ' + block(eq, initial))
            legacy.append('  }')
        legacy.extend(['  ai_will_do = { factor = 2 }', ' }'])
        ideas_by_slot.setdefault(row['legacy_slot'], []).extend(legacy)
        documents.append(f'| {tag} {row["region_name"]} | {row["name"]}；{row["equipment_name"]} | {summary} | {row["factory_name"]}（{row["factory_state"]}） | {localized_focuses(row, "unlock")} |')

    ideas = ['# Generated regional fallback designers. They never coexist with their AAT organization.', 'ideas = {']
    for slot, rows in ideas_by_slot.items():
        ideas.append(' ' + slot + ' = { designer = yes')
        ideas.extend(rows)
        ideas.append(' }')
    ideas.append('}')
    documents.extend(['', '## 满级特色', '', '| 国家 | 所有特质完成后的装备与生产线加成 |', '| --- | --- |'])
    for row in companies:
        full = dict(row['initial_equipment'])
        prod = dict(row['initial_production'])
        for trait in row['traits']:
            for target, values in [(full, trait.get('equipment', {})), (prod, trait.get('production', {}))]:
                for stat, amount in values.items():
                    target[stat] = round(target.get(stat, 0) + amount, 6)
        documents.append('| ' + row['tag'] + ' | ' + stats_text(full) + ('；' + stats_text(prod) if prod else '') + ' |')
    documents.extend(['', '## 国策与成长', '',
                      '18 个普通地区的新局使用通用国策：改进工业解锁企业，先进工业解锁第三项特质，军工复合体解锁末项特质；旧地区国策树分别兼容 eco4、eco7、eco11。巴黎使用首都工业扩张、军工工厂及重型/轻中型装甲研究；科西嘉使用岛屿弹药工场、岛内小武器工业与扩大生产/维持专业化。', '',
                      '军工组织在解锁前仍可查看，并显示完成国策与控制厂址的提示。新增国策提示文本由父级国策集成添加；本模块不修改既有国策奖励与人物。', '',
                      '## 产业依据与架空设计', '',
                      '雷诺、菲夫—里尔、贝利埃、拉特科尔、米其林、彭奥埃与沙泰勒罗以历史企业或工场为基础；其承包结构与所有数值属于剧本设计。其余命名为架空地方联合体，用于表现地区矿冶、船舶、精密、军需与通信产业，未宣称它们是史实公司。', ''])
    for source in design['historical_sources']:
        documents.append('- [' + source['title'] + '](' + source['url'] + ')：' + source['use'])
    documents.extend(['', '## 验证边界', '',
                      '语法与作用域依据本机 HOI4 1.19 的组织 _documentation.md、FRA_organization.txt、00_generic_organization.txt 和 ideas/zzz_generic.txt。装备指标按原版列出的对应装备合法字段生成；特质树自行定义，没有引用被 replace_path 屏蔽的原版模板。', '',
                      '`tools/validate_regional_manufacturers.py` 校验 20 国覆盖、厂址、现行/旧存档国策、DLC 双路径隔离、特质依赖与数值上限，并执行解锁/失去厂址/异国/政治路线的静态情景检查。静态验证不等于游戏引擎实测。', ''])
    return {'mio': '\n'.join(mio) + '\n', 'ideas': '\n'.join(ideas) + '\n',
            'loc': '\n'.join(loc) + '\n', 'doc': '\n'.join(documents)}


def build(check_only=False):
    design = json.loads(DESIGN.read_text(encoding='utf-8'))
    rendered = render(design)
    for kind, relative in OUTPUTS.items():
        path = ROOT / relative
        encoding = 'utf-8-sig' if kind == 'loc' else 'utf-8'
        if check_only:
            assert path.read_text(encoding=encoding) == rendered[kind], relative
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered[kind], encoding=encoding, newline='\n')
    return len(design['manufacturers'])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    print(json.dumps({'manufacturers': build(args.check), 'check_only': args.check}, ensure_ascii=False))
