"""Build 20 region-owned manufacturers from the reviewed authored design.

The mod replaces vanilla organizations, so each tree is deliberately self-contained.
No vanilla template include, script flag, country history or leader file is required.
"""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / 'design/regional-manufacturers.json'
OUTPUTS = {
    'mio': 'mod/common/military_industrial_organization/organizations/sof_regional_manufacturers.txt',
    'ideas': 'mod/common/ideas/sof_regional_manufacturers.txt',
    'loc': 'mod/localisation/simp_chinese/replace/sof_regional_manufacturers_l_simp_chinese.yml',
    'doc': 'docs/REGIONAL-MANUFACTURERS-ZH.md',
}

STAT_NAMES = {
    'reliability': '可靠性', 'build_cost_ic': '装备造价', 'production_cost_factor': '生产成本',
    'armor_value': '装甲', 'maximum_speed': '速度', 'soft_attack': '对人杀伤',
    'hard_attack': '对装甲杀伤', 'ap_attack': '穿甲', 'defense': '防御',
    'naval_range': '航程', 'naval_speed': '航速', 'sub_detection': '对潜探测',
    'sub_attack': '反潜攻击', 'naval_strike_attack': '对舰攻击',
    'air_range': '航程', 'air_agility': '机动性', 'air_bombing': '战略轰炸',
    'air_ground_attack': '对地攻击', 'air_attack': '防空',
    'fuel_consumption': '燃油消耗', 'torpedo_attack': '鱼雷攻击',
    'production_resource_need_factor': '生产资源需求',
    'production_efficiency_gain_factor': '生产效率增长',
    'production_efficiency_cap_factor': '生产效率上限',
    'military_industrial_organization_funds_gain': '组织经费获取',
    'military_industrial_organization_research_bonus': '额外专项科研',
    'military_industrial_organization_task_capacity': '额外并行任务容量',
}


def number(value):
    return format(value, '.6g')


def block(key, values):
    return f'{key} = {{ ' + ' '.join(f'{k} = {number(v)}' for k, v in values.items()) + ' }'


def completed(focuses):
    terms = ' '.join('has_completed_focus = ' + fid for fid in focuses)
    return 'OR = { ' + terms + ' }' if len(focuses) > 1 else terms


def gate(row, focuses, mio=False):
    # PREV is the owning country after entering the literal state scope, including
    # when the owning country is entered through the MIO's documented FROM scope.
    body = (f'has_capitulated = no {completed(focuses)} '
            f'{row["factory_state"]} = {{ is_owned_by = PREV is_fully_controlled_by = PREV }}')
    return 'FROM = { ' + body + ' }' if mio else body


def stats_text(values):
    return '、'.join(STAT_NAMES[k] + (f'{v:+.0f}' if k == 'military_industrial_organization_task_capacity' else f'{v:+.0%}') for k, v in values.items())


def totals(row, design):
    result = {"equipment": dict(row['initial_equipment']), "production": dict(row['initial_production']),
              "organization": dict(design['initial_organization'])}
    for trait in row['traits']:
        for group in result:
            for stat, amount in trait.get(group, {}).items():
                result[group][stat] = round(result[group].get(stat, 0) + amount, 6)
    return result


def localized_focuses(row, field):
    return ' / '.join(row[field + '_names'])


def render(design):
    companies = design['manufacturers']
    mio = ['# Generated by tools/build_regional_manufacturers.py; authored source: design/regional-manufacturers.json.']
    ideas_by_slot = {}
    loc = ['l_simp_chinese:']
    def localize(key, value):
        value = value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        loc.append(f' {key}:0 "{value}"')

    localize('sof_regional_manufacturer_quality_header', '地方工艺')
    localize('sof_regional_manufacturer_production_header', '工场协作')
    documents = [
        '# 地区专属制造商', '',
        '20 个大区代表国家各有一家主打企业。所有企业都限制原籍及当前国家代码，兼容现行通用国策与旧地区树存档；控制厂址并完成实际工业国策后开放。占领其他大区不会获得该地专属企业。', '',
        '4.3.2：每家企业为8层、两条可兼修的成长线，共16项特质。地方工程与工场协作各有8层，原生详情页使用两列纵向布局；各层之间有实际前置，未完成对应工业国策的特质保持灰色。', '',
        '启用《Arms Against Tyranny》时使用原生军工组织：起始专项科研15%、组织经费获取+25%、并行任务容量3。完成工业研究中心后科研提高到20%、经费合计+50%、容量4。没有该 DLC 时同一家企业进入传统设计商对应槽位，聘用费用125政治点、解聘费用10，专项科研15%，装备加成取强化后的起始工艺；不模拟原生军工组织成长。两种版本通过相反DLC条件隔离。', '',
        '起始主打性能8–10%，满成长主打性能通常38–40%，副项约16%；廉价装备路线的装备造价降低25%。工场协作提供生产成本−12%、效率上限和增长各+12%、资源需求−8%。数值只作用于承接的装备、生产线或组织本身；装备造价与生产成本是两个不同的原生指标，按引擎结算。初始的性能或价格代价保留。', '',
        '| 国家 | 企业与主打 | 起始强项 / 代价 | 厂址 | 解锁国策 |',
        '| --- | --- | --- | --- | --- |',
    ]
    for row in companies:
        tag = row['tag']
        key = row['id']
        initial = row['initial_equipment']
        initial_prod = row['initial_production']
        localize(key, row['name'])
        localize(key + '_legacy', row['name'])
        summary = stats_text(initial)
        if initial_prod:
            summary += ('；' if summary else '') + stats_text(initial_prod)
        full = totals(row, design)
        full_summary = '；'.join(stats_text(full[group]) for group in ['equipment', 'production', 'organization'] if full[group])
        conditions = '完全控制' + row['factory_name'] + '，完成“' + localized_focuses(row, 'unlock') + '”。'
        localize(key + '_desc', row['description'] + '\n起始工艺：' + summary + '。专项科研：+15%。\n8层、16项成长：' + full_summary + '。\n解锁：' + conditions)
        localize(key + '_legacy_desc', row['description'] + '\n起始工艺：' + stats_text(initial) + '。专项科研：+15%。\n解锁：' + conditions + '\n传统设计商版本仅提供起始装备工艺，不含军工组织成长。')
        localize(key + '_initial', row['initial_name'])
        localize(key + '_unlock_tt', '完全控制' + row['factory_name'] + '，并完成“' + localized_focuses(row, 'unlock') + '”。')
        localize(key + '_specialize_tt', '完成“' + localized_focuses(row, 'specialize') + '”。')
        localize(key + '_capstone_tt', '完成“' + localized_focuses(row, 'capstone') + '”。')
        mio.extend([
            '', key + ' = {', f' name = {key}', f' icon = GFX_idea_{row["picture"]}',
            f' allowed = {{ original_tag = {tag} tag = {tag} has_dlc = "Arms Against Tyranny" }}',
            f' available = {{ custom_trigger_tooltip = {{ tooltip = {key}_unlock_tt {gate(row, row["unlock"], True)} }} }}',
            ' equipment_type = { ' + ' '.join(row['equipment']) + ' }',
            ' research_categories = { ' + ' '.join(row['research_categories']) + ' }',
            f' research_bonus = {number(design["research_bonus"])}', f' task_capacity = {design["task_capacity"]}',
            ' tree_header_text = { text = sof_regional_manufacturer_quality_header x = 1 }',
            ' tree_header_text = { text = sof_regional_manufacturer_production_header x = 4 }',
            f' initial_trait = {{ name = {key}_initial',
        ])
        if initial:
            mio.append('  ' + block('equipment_bonus', initial))
        if initial_prod:
            mio.append('  ' + block('production_bonus', initial_prod))
        mio.append('  ' + block('organization_modifier', design['initial_organization']))
        mio.append(' }')
        for trait in row['traits']:
            token = key + '_trait_' + str(trait['token_suffix'])
            localize(token, trait['name'])
            details = '；'.join(stats_text(trait[group]) for group in ['equipment','production','organization'] if trait.get(group))
            localize(token + '_desc', f'第{trait["tier"]}层，' + ('地方工程' if trait['branch']=='quality' else '工场协作') + '：' + details + '。')
            mio.extend([f' trait = {{ token = {token} name = {token}',
                        f'  icon = {trait["icon"]}',
                        '  position = { x = ' + str(1 if trait['branch']=='quality' else 4) + ' y = ' + str(trait['tier']-1) + ' }'])
            if trait['parents']:
                mio.append('  all_parents = { ' + ' '.join(key + '_trait_' + str(parent) for parent in trait['parents']) + ' }')
            if trait.get('gate'):
                field = trait['gate']
                mio.append(f'  available = {{ custom_trigger_tooltip = {{ tooltip = {key}_{field}_tt FROM = {{ {completed(row[field])} }} }} }}')
            if trait.get('equipment'):
                mio.append('  ' + block('equipment_bonus', trait['equipment']))
            if trait.get('production'):
                mio.append('  ' + block('production_bonus', trait['production']))
            if trait.get('organization'):
                mio.append('  ' + block('organization_modifier', trait['organization']))
            mio.append(' }')
        mio.extend([' ai_will_do = { factor = 1.15 }', '}'])

        legacy = [f' {key}_legacy = {{', f'  picture = {row["picture"]}',
                  f'  allowed = {{ original_tag = {tag} tag = {tag} NOT = {{ has_dlc = "Arms Against Tyranny" }} }}',
                  '  allowed_civil_war = { always = no }',
                  f'  available = {{ custom_trigger_tooltip = {{ tooltip = {key}_unlock_tt {gate(row, row["unlock"])} }} }}',
                  f'  cancel = {{ NOT = {{ {gate(row, row["unlock"])} }} }}',
                  '  cost = 125', '  removal_cost = 10',
                  '  research_bonus = { ' + ' '.join(k + ' = ' + number(design['research_bonus']) for k in row['research_categories']) + ' }']
        # Production resource/efficiency modifiers do not have a per-line legacy
        # equivalent. The fallback intentionally carries only equipment effects.
        if initial:
            legacy.append('  equipment_bonus = {')
            for eq in row.get('legacy_equipment', row['equipment']):
                legacy.append('   ' + block(eq, initial))
            legacy.append('  }')
        legacy.extend(['  ai_will_do = { factor = 2 }', ' }'])
        ideas_by_slot.setdefault(row['legacy_slot'], []).extend(legacy)
        documents.append(f'| {tag} {row["region_name"]} | {row["name"]}；{row["equipment_name"]} | {summary} | {row["factory_name"]}（{row["factory_state"]}） | {localized_focuses(row, "unlock")} |')

    ideas = ['# Generated regional fallback designers. They never coexist with their AAT organization.', 'ideas = {']
    for slot, rows in ideas_by_slot.items():
        ideas.append(' ' + slot + ' = { designer = yes')
        ideas.extend(rows)
        ideas.append(' }')
    ideas.append('}')
    documents.extend(['', '## 满级特色', '', '| 国家 | 所有特质完成后的装备与生产线加成 |', '| --- | --- |'])
    for row in companies:
        full = totals(row, design)
        documents.append('| ' + row['tag'] + ' | ' + '；'.join(stats_text(full[group]) for group in ['equipment','production']) + ' |')
    documents.extend(['', '## 国策与成长', '',
                      '18个普通地区的新局使用通用国策：改进工业解锁企业，先进工业解锁第3–5层，军工复合体解锁第6–8层；旧地区国策树分别兼容eco4、eco7、eco11。巴黎使用首都工业扩张、军工工厂及重型/轻中型装甲研究；科西嘉使用岛屿弹药工场、岛内小武器工业与扩大生产/维持专业化。', '',
                      '原版通用模板有12–15项特质，单项5%～10%性能提升很常见。本轮保留原生组织经验、点数、前置和装备适用方式，把布局扩展为8层；原版参照记录见 `design/vanilla-mio-growth-reference.json`。', '',
                      '组织ID和原来的trait_1至trait_4全部保留，新特质使用新增token；旧组织已有的四项选择不会因改名或删除ID而丢失。组织已有点数和等级不重置。原生装备设计的更新、真实旧档中的组织数值和滚动显示仍须实机检查。', '',
                      '军工组织在解锁前仍可查看，并显示完成国策与控制厂址的提示。新增国策提示文本由父级国策集成添加；本模块不修改既有国策奖励与人物。', '',
                      '## 产业依据与架空设计', '',
                      '雷诺、菲夫—里尔、贝利埃、拉特科尔、米其林、彭奥埃与沙泰勒罗以历史企业或工场为基础；其承包结构与所有数值属于剧本设计。其余命名为架空地方联合体，用于表现地区矿冶、船舶、精密、军需与通信产业，未宣称它们是史实公司。', ''])
    for source in design['historical_sources']:
        documents.append('- [' + source['title'] + '](' + source['url'] + ')：' + source['use'])
    documents.extend(['', '## 验证边界', '',
                      '语法与作用域依据本机 HOI4 1.19 的组织 _documentation.md、FRA_organization.txt、00_generic_organization.txt 和 ideas/zzz_generic.txt。装备指标按原版列出的对应装备合法字段生成；特质树自行定义，没有引用被 replace_path 屏蔽的原版模板。', '',
                      '`tools/validate_regional_manufacturers.py` 校验 20 国覆盖、厂址、现行/旧存档国策、DLC 双路径隔离、特质依赖与数值上限，并执行解锁/失去厂址/异国/政治路线的静态情景检查。静态验证不等于游戏引擎实测。', ''])
    return {'mio': '\n'.join(mio) + '\n', 'ideas': '\n'.join(ideas) + '\n',
            'loc': '\n'.join(loc) + '\n', 'doc': '\n'.join(documents)}


def build(check_only=False):
    design = json.loads(DESIGN.read_text(encoding='utf-8'))
    rendered = render(design)
    for kind, relative in OUTPUTS.items():
        path = ROOT / relative
        encoding = 'utf-8-sig' if kind == 'loc' else 'utf-8'
        if check_only:
            assert path.read_text(encoding=encoding) == rendered[kind], relative
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered[kind], encoding=encoding, newline='\n')
    return len(design['manufacturers'])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    print(json.dumps({'manufacturers': build(args.check), 'check_only': args.check}, ensure_ascii=False))
